name: Remove String

on:
  workflow_dispatch:

jobs:
  remove-string:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Remove specified string from all HTML files
      run: |
        find . -type f -name '*.html' -exec sed -i 's|=======||g' {} +
        find . -type f -name '*.html' -exec sed -i 's|>>>>>>> 784da82d7cd708fc8c4b9dabfc0367adb69b16d5||g' {} +
        
    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        if git commit -m "Remove specific string from HTML files"; then
          git push
        fi
