name: Remove String

on:
  workflow_dispatch:

jobs:
  remove-string:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Remove specified string from all HTML files
      run: |
        find . -type f -name '*.html' -exec sed -i "s|<<<<<<< HEAD||g" {} +

    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        if git commit -m "Remove specific string from HTML files"; then
          git push
        fi
